name: Package and release Prosody plugins

on: push

jobs:
  run-ci:
    name: package and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Build and package Jitsi meet libs folder
      run: npm install
    - run: make
    - run: npm run zip-jitsi-meet-libs

    - name: Release and publish prosody plugins
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: jitsi-meet-libs.zip
